import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Hulu clone idk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full bg-bluish text-gray-300">
        <Header />

      </div>
    </div>
  )
}
